### PR TITLE
Modifications

### PR DESCRIPTION
**Pull request by kimanimichael**
I made some modifications

## Summary by CodeRabbit

- **Bug Fixes**
	- Corrected the pin assignment for the potentiometer to use the appropriate analog pin A5 instead of pin 8, ensuring proper functionality.

### CODE REVIEW

**Comment by rodneyosodo** [comment]
@Mike-Kimani I am getting a merge error

**Comment by rodneyosodo** [comment]
@Mike-Kimani rebase

**Comment by rodneyosodo** [comment]
@Mike-Kimani rebase

**Comment by kimanimichael** [comment]
> @Mike-Kimani rebase

@rodneyosodo Done

**Pull request merged**
